# vim: ts=2 sw=2 expandtab ai
---
knative_patch:
  file: /var/lib/minishift/base/kube-apiserver/master-config.yaml
  key: admissionConfig
  value: 
    pluginConfig:
      MutatingAdmissionWebhook:
        configuration:
          apiVersion: v1
          disable: false
          kind: DefaultAdmissionConfig
      ValidatingAdmissionWebhook:
        configuration:
          apiVersion: v1
          disable: false
          kind: DefaultAdmissionConfig

